### PR TITLE
Add more camera controls, progress bars, seed to the sampler and shape parameters

### PR DESCRIPTION
**Pull request by kijai**
I could not find proper info on what the shape parameters should be called, currently they are just my guesses.

### CODE REVIEW

**Comment by kijai** [comment]
> The names fit well I think. Can you put betas_batch into SMPL instance (e.g. smpl[2]["shape_params"])? That makes a bit more sense ig.
You mean like this?
image

**Comment by kijai** [comment]
Exposed the render frame size as well: 
image

**Comment by kijai** [comment]
Learned some pyrender and optimized the SMPL mesh rendering loop a lot, at 512p it now only takes 3 seconds to render 100 frames.

**Comment by Fannovel16** [comment]
> > The names fit well I think. Can you put betas_batch into SMPL instance (e.g. smpl[2]["shape_params"])? That makes a bit more sense ig.
> > You mean like this?
> > image

Yeah

**Pull request merged**
